EAristotelWeb/Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EAristotelBLL;
using EAristotelBLL.services;
using EAristotelDomain.model.exam;
using EAristotelWeb.Models;
using WebGrease.Css.Extensions;

namespace EAristotelWeb.Controllers
{
    public class ExamController : ControllerBLL
    {
        // GET: Exam
        public ActionResult Index()
        {
            return View(Provider.ExamService.GetAllExams());
        }

        // GET: Exam/Details/5
        public ActionResult TakeExam(int id)
        {
            Exam e;
            //load the associations needed for this View
            using (BllContext c = BllContextFactory.CreateContext())
            {
                e = loadExamViewModel(id, c);
            }

            ViewBag.Results = false;
            return View(e);
        }

        private Exam loadExamViewModel(int id, BllContext c)
        {
            Exam e = Provider.ExamService.GetExam(id, c);

            e.Repository.Id = e.Repository.Id;
            e.Repository.Name = e.Repository.Name;

            e.ExamTasks = e.ExamTasks.ToList();
            e.ExamTasks.ForEach(et =>
            {
                et.Content = et.Content;

                et.OfferedSolutions.ForEach(os =>
                {
                    os.Id = os.Id;
                    os.Result = os.Result;
                });

            });

            return e;
        }

        // POST: 
        [HttpPost]
        public ActionResult TakeExam(ExamEvaluationModel submittedExam)
        {
            Exam e;
            ExamEvaluationModel model;
            //load the associations needed for this View
            using (BllContext c = BllContextFactory.CreateContext())
            {
                model = Provider.ExamService.EvaluateExam(submittedExam, c);
                e = loadExamViewModel(model.Id, c);
            }

            ViewBag.EvaluationModel = model;
            ViewBag.Results = true;
            return View(e);
        } 
    }


}

EAristotelWeb/Controllers/MaterialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EAristotelBLL;
using EAristotelBLL.services;
using EAristotelDomain.model.material;

namespace EAristotelWeb.Controllers
{
    public class MaterialController : ControllerBLL
    {
        // GET: Exercise
        public ActionResult Index()
        {
            return View(Provider.MaterialService.GetAllMaterials());
        }

        // GET: Exercise/Details/5
        public ActionResult Details(int id)
        {
            Material m;
            using (BllContext c = BllContextFactory.CreateContext())
            {
                m = Provider.MaterialService.GetMaterial(id, c);
                ViewBag.RepoId = m.Repository.Id;
                ViewBag.RepoName = m.Repository.Name;
            }
            return View(m);
        }

    }
}

EAristotelWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" async
            src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("e-Aristotel", "Index", "Home", new {area = ""}, new {@class = "navbar-brand navbar-text"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Repositories", "Index", "Repositories", null, new { @class = "navbar-text" })</li>
                <li>@Html.ActionLink("Exercises", "Index", "Exercise", null, new { @class = "navbar-text" })</li>
                <li>@Html.ActionLink("Materials", "Index", "Material", null, new { @class = "navbar-text" })</li>
                <li>@Html.ActionLink("Exams", "Index", "Exam", null, new { @class = "navbar-text" })</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "navbar-text" })</li>
                <li></li>
            </ul>
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                @using (Html.BeginForm("Search", "Repositories", "", FormMethod.Get, new {@class = "navbar-form"}))
                {
                    <h2>
                        <div class="input-group">
                            <input class="form-control" name="query" placeholder="Search..">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <span type="submit" class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </button>
                            </span>
                        </div>
                    </h2>
                }
            </div>
            <!--@Html.Partial("_LoginPartial")-->
        </div>
    </div>
</div>
    <br/>
<div class="container body-content">
    @Scripts.Render("~/bundles/jquery")
    <br/>
    @RenderBody()
    <hr/>
    <footer>
        <p>Objektno oblikovanje &copy; Seminar @DateTime.Now.Year</p>
    </footer>
</div>


@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>