EAristotelWeb/Controllers/ExerciseController.cs
using EAristotelBLL;
using EAristotelBLL.factories;
using EAristotelBLL.services;
using EAristotelDomain.model.exercise;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace EAristotelWeb.Controllers
{
    public class ExerciseController : ControllerBLL
    {
        // GET: Exercise
        public ActionResult Index()
        {
            return View(Provider.ExerciseService.GetAllExercises());
        }

        // GET: Exercise/Details/5
        public ActionResult Details(int id)
        {
            Exercise e;
            using (BllContext c = BllContextFactory.CreateContext())
            {
                e = Provider.ExerciseService.GetExercise(id, c);
                ViewBag.RepoId = e.Repository.Id;
                ViewBag.RepoName = e.Repository.Name;
                ViewBag.Solutions = e.Solutions.ToList();
            }
            return View(e);
        }

        // GET: Exercise/Create
        public ActionResult Create()
        {
            ViewBag.Repos = new SelectList(Provider.LeRepositoryService.GetRepositories(), "Id", "Name");
            return View();
        }

        // POST: Exercise/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                string name = collection.Get("Name");
                string content = collection.Get("Content");
                int repositoryId = int.Parse(collection.Get("Repository"));
                string tags = collection.Get("Tag");

                Exercise exercise = ExerciseFactory.CreateExercise(name, content);
                if (!string.IsNullOrWhiteSpace(tags))
                {
                    Regex.Replace(tags, @"\s+", "");
                    exercise.Tags = tags.Split(';').ToList();
                }

                Provider.ExerciseService.CreateExercise(repositoryId, exercise);

                return RedirectToAction("Details", new { Id = exercise.Id });
            }
            catch
            {   
                ViewBag.Repos = new SelectList(Provider.LeRepositoryService.GetRepositories(), "Id", "Name");
                ViewBag.Error = "Error creating new exercise";
                return View();
            }
        }

        // GET: Exercise/Edit/5
        public ActionResult Edit(int id)
        {
            return View(Provider.ExerciseService.GetExercise(id));
        }

        // POST: Exercise/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                string name = collection.Get("Name");
                string content = collection.Get("Content");

                Exercise exercise = Provider.ExerciseService.GetExercise(id);
                exercise.Name = name;
                exercise.Content = content;

                Provider.ExerciseService.UpdateExercise(exercise);

                return RedirectToAction("Details", new { Id = exercise.Id });
            }
            catch
            {
                ViewBag.Repos = new SelectList(Provider.LeRepositoryService.GetRepositories(), "Id", "Name");
                ViewBag.Error = "Error creating new exercise";
                return View();
            }
        }

        // GET: Exercise/CreateSolution
        public ActionResult CreateSolution(int? eId)
        {
            ViewBag.Exercises = new SelectList(Provider.ExerciseService.GetAllExercises(), "Id", "Name", eId);
            return View();
        }

        // POST: Exercise/CreateSolution
        [HttpPost]
        public ActionResult CreateSolution(FormCollection collection)
        {
            int exerciseId = int.Parse(collection.Get("Exercise"));
            string result = collection.Get("Result");
            string stepByStep = collection.Get("StepByStep");

            Exercise e = Provider.ExerciseService.GetExercise(exerciseId);
            ExerciseSolution es = ExerciseFactory.CreateExerciseSolution(result, stepByStep);
            es.Exercise = e;
            Provider.ExerciseService.AddSolution(exerciseId, es);
            return RedirectToAction("Details", new { Id = e.Id });
        }
    }
}

EAristotelWeb/Controllers/RepositoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EAristotelBLL;
using EAristotelBLL.services;
using EAristotelDomain.model.repository;
using EAristotelWeb.Models;

namespace EAristotelWeb.Controllers
{
    public class RepositoriesController : ControllerBLL
    {
        // GET: Repositories
        public ActionResult Index()
        {
            return View(Provider.LeRepositoryService.GetTopLevelRepositories());
        }

        // GET: Repositories/Details/5
        public ActionResult Details(int id)
        {
            RepositoryDetailsModel repo;
            using (BllContext context = BllContextFactory.CreateContext())
            {
                repo= new RepositoryDetailsModel(Provider.LeRepositoryService.GetRepository(id, context));
            }

            ViewBag.Title = repo.Name;
            return View(repo);
        }

        // GET: Repositories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Repositories/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Repositories/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Repositories/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Repositories/Delete/5
        public ActionResult Delete(int id)
        {
            //admin only
            //Provider.LeRepositoryService.RemoveRepository(id);

            return RedirectToAction("Index");
        }

        // POST: Repositories/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Search(string query)
        {
            RepositoryDetailsModel repo;
            using (var context=BllContextFactory.CreateContext())
            {
                repo = new RepositoryDetailsModel(Provider.LeRepositoryService.SearchEverythingForRepo(query, context));
            }

            ViewBag.Title = "Search results for '" + query + "'";
            return View("Details", repo);
        }
    }
}

EAristotelWeb/Views/Exercise/Create.cshtml
@model EAristotelDomain.model.exercise.Exercise

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
    showProcessingMessages: false,
    });
</script>
<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML"></script>

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger fade in">
        <strong>Danger!</strong> Error creating exercise.
    </div>
}

@{
    ViewBag.Title = "Create new exercise";
}

<h2>Create new exercise</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Exercise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Repository, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.DropDownList("Repository", (SelectList) ViewBag.Repos, " -- Select -- ", new { id = "repo", @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <p>Preview:</p>
            <div class="col-md-10">
                <div id="MathPreview" style="border:1px solid; padding: 3px; width:50%; margin-top:5px"></div>
                <div id="MathBuffer" style="border:1px solid; padding: 3px; width:50%; margin-top:5px; visibility:hidden; position:absolute; top:0; left: 0"></div>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Tag", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("Tag", new { htmlAttributes = new { @class = "form-control", placeholder = "default;tags;" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customscripts")
}

EAristotelWeb/Views/Exercise/CreateSolution.cshtml
@model EAristotelDomain.model.exercise.ExerciseSolution

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
    showProcessingMessages: false,
    });
</script>
<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML"></script>

@{
    ViewBag.Title = "CreateSolution";
}

<h2>CreateSolution</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ExerciseSolution</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Exercise, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Exercise", (SelectList)ViewBag.Exercises, " -- Select -- ", new { id = "exer", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Result, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Result, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Result, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StepByStep, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.StepByStep, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StepByStep, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <p>Preview:</p>
            <div class="col-md-10">
                <div id="MathPreview" style="border:1px solid; padding: 3px; width:50%; margin-top:5px"></div>
                <div id="MathBuffer" style="border:1px solid; padding: 3px; width:50%; margin-top:5px; visibility:hidden; position:absolute; top:0; left: 0"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customscripts")
}

EAristotelWeb/Views/Exercise/Details.cshtml
@model EAristotelDomain.model.exercise.Exercise

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Exercise</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.Label("Repository")
        </dt>

        <dd>
            @Html.ActionLink((string) ViewBag.RepoName, "Details", "Repositories", new { id = ViewBag.RepoId }, null)
        </dd>

    </dl>
    
    <hr/>
    <a href="#" id="showSolutionsButton"> Show solutions..</a>    
    <div id="solutionContainter" class="container">
        <hr />
        
        <div class="panel panel-success">
            <div class="panel-heading">Best solution</div>
            <div class="panel-body">
                @if (Model.BestSolution != null)
                {
                    <p>@Model.BestSolution.StepByStep</p>
                    <br />
                    <strong>Result: </strong><p>@Model.BestSolution.Result</p>

                }
                else
                {
                    <p>There is no best solution yet</p>
                }
            </div>
        </div>
        
        <hr />
        <div class="panel panel-default">
            <div class="panel-heading">All solutions | @Html.ActionLink("Create new solution", "CreateSolution", new { eId = Model.Id })</div>
            <div class="panel-body">
                @foreach (var sol in ViewBag.Solutions)
                {
                    <div class="col-md-12">@sol.StepByStep</div>
                    <br />
                    <strong>Result: </strong><span>@sol.Result</span>
                    <hr />
                }
            </div>
        </div>
    </div>
    <hr />
    <script>
        $("#solutionContainter").hide();
        $("#showSolutionsButton").click(function() {
            $("#solutionContainter").show();
        });
    </script>
</div>
<p>
    <!--@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |-->
    @Html.ActionLink("Back to Repository", "Details", new { Controller = "Repositories", Id = @Model.Repository.Id })
</p>

EAristotelWeb/Views/Exercise/Edit.cshtml
@model EAristotelDomain.model.exercise.Exercise

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
    showProcessingMessages: false,
    });
</script>
<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML"></script>

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Exercise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>Preview:</p>
            <div class="col-md-10">
                <div id="MathPreview" style="border:1px solid; padding: 3px; width:50%; margin-top:5px"></div>
                <div id="MathBuffer" style="border:1px solid; padding: 3px; width:50%; margin-top:5px; visibility:hidden; position:absolute; top:0; left: 0"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customscripts")
}

EAristotelWeb/Views/Exercise/Index.cshtml
@model IEnumerable<EAristotelDomain.model.exercise.Exercise>

@{
    ViewBag.Title = "Exercises";
}

<h2>All exercises</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            <!--@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |-->
            @Html.ActionLink("Details", "Details", new { id=item.Id })
        </td>
    </tr>
}

</table>